version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: franchise-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: franchise_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - franchise-network

volumes:
  mongodb_data:
    driver: local

networks:
  franchise-network:
    driver: bridge