spring:
  application:
    name: franchise-management-api

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/franchise_db}
      auto-index-creation: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    co.com.nequi.api.franchise_management_api: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"